<?php

require_once('Settings/SettingsContainerInterface.php');
require_once('Settings/SettingsContainerAbstract.php');
require_once('QRCode/QROptionsTrait.php');
require_once('QRCode/QROptions.php');
require_once('QRCode/Output/QROutputInterface.php');
require_once('QRCode/Output/QROutputAbstract.php');
require_once('QRCode/Output/QRImage.php');
require_once('QRCode/Output/QRMarkup.php');
require_once('QRCode/Output/QRString.php');
require_once('QRCode/Output/QRFpdf.php');
require_once('QRCode/Output/QRImagick.php');
require_once('QRCode/QRCodeException.php');
require_once('QRCode/Output/QRCodeOutputException.php');
require_once('QRCode/Data/QRMatrix.php');
require_once('QRCode/Data/QRCodeDataException.php');
require_once('QRCode/Data/QRDataInterface.php');
require_once('QRCode/Helpers/BitBuffer.php');
require_once('QRCode/Helpers/Polynomial.php');
require_once('QRCode/Data/QRDataAbstract.php');
require_once('QRCode/Data/Byte.php');
require_once('QRCode/Data/Number.php');
require_once('QRCode/Data/MaskPatternTester.php');
require_once('QRCode/QRCode.php');
require_once('Customs/QRImageWithLogo.php');
require_once('Customs/QRImageWithText.php');